#Die docker-compose.yml muss übergeordnet über dem Backend und Frontend liegen
version: "3.8"
services:
  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./backend_production_line/productionline
    image: productionlinebackend:1.0
    container_name: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/productionlinedb?allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - backend-db
      - backend-frontend

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productionlinedb
    networks:
      - backend-db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 1

  frontend:
    image: productionlinefrontend:1.0
    build:
      context: ./frontend_production_line
    container_name: frontend
    ports:
      - 5173:80
    depends_on:
      - backend
    networks:
      - backend-frontend

networks:
  backend-db:
  backend-frontend:
