version: "3.8"
services:
  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
    image: productionlinebackend:1.0
    container_name: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/productionlinedb?allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - backend-db

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productionlinedb
    #      MYSQL_USER: root
    #      MYSQL_PASSWORD: root
    networks:
      - backend-db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 2

networks:
  backend-db:
